---
title: "structure"
author: "Toshikazu, Matsumura"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{structure}
  %\VignetteEngine{knitr::rmarkdown}
---


```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(moranajp)
library(tidyverse)
library(grid)
```

```{r}
cols <- c("text_id", "\\u8868\\u5c64\\u5f62", "\\u54c1\\u8a5e", 
          "\\u54c1\\u8a5e\\u7d30\\u5206\\u985e1", "\\u539f\\u5f62") %>%
        stringi::stri_unescape_unicode()
surface_form  <- stringi::stri_unescape_unicode("\u8868\u5c64\u5f62")
original_form <- stringi::stri_unescape_unicode("\u539f\u5f62")
s_id <- "sentence_id"
data(review_sudachi_c)
review_sudachi_c <- 
  review_sudachi_c %>%
  dplyr::mutate_all(stringi::stri_unescape_unicode) %>%
  magrittr::set_colnames(stringi::stri_unescape_unicode(colnames(.))) %>%
  dplyr::mutate(`:=`(text_id, as.numeric(text_id))) %>%
  dplyr::select(dplyr::all_of(cols)) %>%
  clean_sudachi_local() %>%
  delete_parenthesis()

review <- 
  review_sudachi_c %>%
  dplyr::filter(.data[[s_id]] < 20) %>%
  dplyr::filter(pos_1 != stringi::stri_unescape_unicode("\u52d5\u8a5e")) %>%
  dplyr::filter(pos_2 != stringi::stri_unescape_unicode("\u6570\u8a5e")) %>%
  dplyr::filter( !stringr::str_detect(term, "[A-z]+") ) %>%
  dplyr::mutate(`:=`(w, 
    stringi::stri_width( .data[[surface_form]]) )) %>%
  dplyr::mutate(`:=`(x, 
    purrr::accumulate(w, `+`) 
    )) %>%
  align_sentence()

review %>%
  ggplot(aes(x, .data[[s_id]], label = term)) + 
  geom_text() + 
  theme_bw()
```

```{r, eval = FALSE}
review  %>%
  #   dplyr::filter(text_id < 5) %>%
  dplyr::select(term, x) %>%
  dplyr::group_by(term, x) %>%
  tally() %>%
  arrange(desc(n))

grid::grid.newpage()
vp <- viewport(width = max(text$x))
grid::grid.text(text[[surface_form]], text$x, just = c("right", "centre"), vp = vp)

```

```{r, eval = FALSE}
review_mecab   %>% colnames() %>% stringi::stri_unescape_unicode()
review_ginza   %>% colnames() %>% stringi::stri_unescape_unicode()
review_chamame %>% colnames() %>% stringi::stri_unescape_unicode()
```

```{r, eval = FALSE}
width <- function(x, unit = "mm"){
  grid::stringWidth(x) %>%
  grid::convertWidth(unit = unit)
}
one_jp_width <- function(unit = "mm"){
  space <- stringi::stri_unescape_unicode("\u3000") 
  grid::stringWidth(space) %>%
  grid::convertWidth(unit = unit)
}
```
